#ifndef FRAMEWORK_CONSTANTS_H
#define FRAMEWORK_CONSTANTS_H

//#define LOADLOGGING_ENABLED
//#define DELETELOGGING_ENABLED
//#define GLGENLOGGING_ENABLED

#include "Log.hpp"

// Texture needs access to this at the moment which is unfortunate
enum class TextureID {
	NO_TEXTURE,
	STONE_TEXTURE,
	DIRT_TEXTURE,
	TILE_TEXTURE,
	REOHANG_TEXTURE,
	TESTSPRITESHEET_TEXTURE,
	ME_TEXTURE,
	CAMERA_FRAME_TEXTURE,
	REO_TEST,
	TILESHEET_TEXTURE
};


#endif